repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      # Fast hooks - run on every commit
      - id: fmt
        name: fmt
        description: Format code with rustfmt
        entry: cargo fmt --
        language: rust
        types: [rust]

      - id: clippy-changed
        name: clippy (changed files only)
        description: Run clippy linter on changed files only
        entry: bash -c 'FILES=$(git diff --name-only --cached | grep "\.rs$" | xargs); if [ -n "$FILES" ]; then cargo clippy --quiet -- -D warnings; fi'
        language: system
        pass_filenames: false
        verbose: true

      # Heavier hooks - run on push only
      - id: clippy-full
        name: clippy (full workspace)
        description: Run clippy linter on the entire workspace
        entry: cargo clippy --workspace -- -D warnings
        language: rust
        pass_filenames: false
        stages: [pre-push]

      - id: test
        name: test
        description: Run cargo tests
        entry: cargo test --workspace
        language: rust
        pass_filenames: false
        stages: [pre-push]

      - id: coverage
        name: coverage
        description: Check test coverage
        entry: cargo tarpaulin --ignore-tests --fail-under 80
        language: rust
        pass_filenames: false
        stages: [pre-push]
